[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"

[[constraint]]
  #name = "github.com/xanzy/go-gitlab"
  #version = "0.16.1"
  name = "github.com/manland/go-gitlab"
  branch = "improveWebHook"
